### ISSUE TITLE
minor comments

### ISSUE THREAD

**Issue by thorade** [Dennis-van-Gils/python-fluidprop#1]
Hi,
just out of curiosity, what does this do different or better than the CoolProp python wrapper?
https://pypi.org/project/CoolProp/

And, are you aware of this software:
https://asimptote.com/fluidprop/
It happens to have the same name

**Comment by miguellords** [comment]
try this
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Dennis-van-Gils** [comment]
Hi Thorade. This fluidprop library is a low-level interface to CoolProp. A glorified pocket calculator for thermodynamic fluid properties, only as a function of temperature and pressure. That's it. Made for quick inspection via the command line interface or fast data-analysis in your scripts, used for our most common research in our research group.
